"""rlm_qa_agent

Usage:
    uv run python examples/rlm_qa/rlm_qa_agent.py

Description:
    - Uses dspy.RLM to perform interactive Q&A against a codetwine knowledge file
    - Accepts either project_knowledge.json or project_knowledge.sqlite as input
    - Generates answers by manipulating JSON with Python code via PythonInterpreter (Deno/Pyodide sandbox)

Prerequisites:
    - project_knowledge.json or project_knowledge.sqlite must be generated by running
      uv run python main.py (KNOWLEDGE_FORMAT selects which one is written)
    - LLM_API_KEY environment variable must be set to the LLM provider's API key
    - dspy package must be installed (uv sync --extra examples)
    - Deno runtime must be installed (curl -fsSL https://deno.land/install.sh | sh)
"""

import inspect
import json
import os
import subprocess
import sys
import dspy
from dspy.primitives.python_interpreter import PythonInterpreter
from codetwine import knowledge_db
import qa_tools


# ===== Configuration (modify to match your environment) =====

# LLM model name used by dspy.LM (litellm format)
# Examples: "anthropic/<model>", "openai/<model>", "gemini/<model>", "ollama/<model>"
LLM_MODEL = "anthropic/claude-opus-4-6"

# Sub-LLM model name used for llm_query/llm_query_batched within RLM sandbox
SUB_LLM_MODEL = "anthropic/claude-sonnet-4-6"

# API key (obtained from environment variable)
LLM_API_KEY = os.environ.get("LLM_API_KEY", "")

# API base URL (set when using non-standard endpoints, e.g. Ollama, Azure)
# LLM_API_BASE = "http://localhost:11434"
LLM_API_BASE = None

# Natural language for answers
OUTPUT_LANGUAGE = "English"

# Path to the target knowledge file. Either a project_knowledge.json written by
# KNOWLEDGE_FORMAT=json / both, or a project_knowledge.sqlite written by
# KNOWLEDGE_FORMAT=sqlite / both
TARGET_KNOWLEDGE_PATH = f"{os.path.dirname(__file__)}/../sample_output/codetwine/project_knowledge.json"


# ===== Signature instructions template =====
# Template variables (embedded via .replace()):
#   <<<DOC_SCHEMA>>> : result of build_doc_schema()
#   <<<RLM_OUTPUT_LANGUAGE>>> : value of OUTPUT_LANGUAGE
INSTRUCTIONS_TEMPLATE = """You are an agent that explores a project design document in JSON format.
Manipulate the input project_data variable with Python code and answer the question.
Always write your answer in <<<RLM_OUTPUT_LANGUAGE>>>.

## Important rules
**Do not print() the entire project_data**: The data is too large and the output will be truncated. Extract and print() only the parts you need.

## Investigation rules
- Always verify your answer against the actual source code before responding. Do not answer from memory or assumption alone.
  - Use `definitions[].context` to check specific function/class source code
  - Use `read_source_file(file_path)` when you need the entire file content
  - When answering about behavior, logic, or data flow, read the relevant code and confirm the implementation matches your answer.
- If information is not found in the codebase, say so. Never fabricate or guess.

## JSON Schema

### Top level
- `project_name` (str): Project name
- `project_dependencies` (array): Project-wide dependency graph (for understanding overall structure, entry point search)
- `files` (array): Per-file detailed information (dependency details, design documents, source code)

### project_dependencies[]
- `file` (str): File path
- `summary` (str|null): Summary of the file (null if not yet generated)
- `callers` (str[]): Files calling this file (dependents)
- `callees` (str[]): Files this file calls (dependencies)

### files[]
- `file` (str): File path
- `file_dependencies` (object): Dependency details
- `doc` (object): Design document

### file_dependencies.definitions[]
- `name` (str): Function/class name
- `type` (str): Definition type ("function_definition", "class_definition", etc.)
- `start_line` (int): Start line number (1-indexed)
- `end_line` (int): End line number (1-indexed)
- `context` (str): Full source code of the definition

### file_dependencies.callee_usages[] (dependencies used by this file)
- `lines` (int[]): Usage line numbers within this file
- `name` (str): Function/class name being used
- `from` (str): Dependency file path
- `target_context` (str): Full source code of the dependency function/class

### file_dependencies.caller_usages[] (dependents using this file)
- `lines` (int[]): Usage line numbers within the dependent file
- `name` (str): Function/class name being used
- `file` (str): Dependent file path
- `usage_context` (str): Source code of the usage location in the dependent

### doc
- `summary` (str): Summary of the file
- `sections` (array): Design document section array. Each element has `id` (str), `title` (str), `content` (str)

<<<DOC_SCHEMA>>>

## Code examples

### Keyword search (across all fields)
```python
keyword = "search_term"
kw = keyword.lower()
for f in project_data["files"]:
    fp = f["file"]
    deps = f["file_dependencies"]
    if kw in f["doc"]["summary"].lower():
        print(f"summary: {fp}")
    for s in f["doc"]["sections"]:
        if kw in s["content"].lower():
            print(f"section: {fp} / {s['title']}")
    for d in deps["definitions"]:
        if kw in d.get("context", "").lower():
            print(f"definition: {fp} / {d['name']}")
    for u in deps["callee_usages"]:
        if u.get("target_context") and kw in u["target_context"].lower():
            print(f"callee: {fp} -> {u['from']} / {u['name']}")
    for c in deps["caller_usages"]:
        if c.get("usage_context") and kw in c["usage_context"].lower():
            print(f"caller: {c['file']} -> {fp} / {c['name']}")
```

### Entry point search and dependency investigation
```python
# Entry point search
entry_points = [f["file"] for f in project_data["project_dependencies"] if not f["callers"]]
print(entry_points)

# Investigate dependencies and dependents of a file
target = [f for f in project_data["files"] if "module_name" in f["file"]][0]
print("Dependencies:", [(u["from"], u["name"]) for u in target["file_dependencies"]["callee_usages"]])
print("Dependents:", [(c["file"], c["name"]) for c in target["file_dependencies"]["caller_usages"]])
```
"""


def build_doc_schema(project_data: dict) -> str:
    """
    Extract doc section list from the loaded knowledge data
    and dynamically generate text to embed in instructions.

    Args:
        project_data: Loaded knowledge data

    Returns:
        Text listing doc sections
    """
    sections = []
    for file_entry in project_data.get("files", []):
        doc = file_entry.get("doc", {})
        if doc.get("sections"):
            sections = doc["sections"]
            break

    section_rows = [f"| `{s['id']}` | {s['title']} |" for s in sections]
    section_table = "| id | title |\n|---|---|\n" + "\n".join(section_rows)

    return "**doc.sections list for this project (each section has content in its content field):**\n" + section_table


def _load_from_sqlite(db_path: str) -> dict:
    """Read a project_knowledge.sqlite into the same dict shape as project_knowledge.json.

    Args:
        db_path: File path to project_knowledge.sqlite.

    Returns:
        A dict with "project_name" / "project_dependencies" / "files" keys.
    """
    connection = knowledge_db.open_knowledge(db_path)
    try:
        return {
            "project_name": knowledge_db.get_project_name(connection) or "",
            "project_dependencies": list(knowledge_db.iter_dependencies(connection)),
            "files": list(knowledge_db.iter_files(connection)),
        }
    finally:
        connection.close()


def load_project(knowledge_path: str):
    """Load the knowledge file and set qa_tools module variables.

    A ".sqlite" path is read through codetwine.knowledge_db; any other path is read as
    project_knowledge.json. Both produce the same project_data structure.

    The RLM sandbox receives project_data as a whole, so the entries are materialized
    here in either case.

    Args:
        knowledge_path: File path to project_knowledge.json or project_knowledge.sqlite.
    """
    if knowledge_path.endswith(".sqlite"):
        qa_tools.project_data = _load_from_sqlite(knowledge_path)
    else:
        with open(knowledge_path, "r", encoding="utf-8") as f:
            qa_tools.project_data = json.load(f)

    qa_tools.base_dir = os.path.dirname(knowledge_path)

    print(f"[OK] Loaded {len(qa_tools.project_data['files'])} files from project '{qa_tools.project_data['project_name']}'")


def create_interpreter() -> PythonInterpreter:
    """Create a PythonInterpreter configured with --node-modules-dir=false and --allow-read for Deno 2.x.

    Returns:
        PythonInterpreter: Interpreter with Deno command configured
    """
    # Get the path to runner.js
    primitives_dir = os.path.dirname(inspect.getfile(PythonInterpreter))
    runner_path = os.path.join(primitives_dir, "runner.js")

    # Locate Deno cache directory
    deno_dir = os.environ.get("DENO_DIR")
    if not deno_dir:
        try:
            result = subprocess.run(
                ["deno", "info", "--json"],
                capture_output=True, text=True, check=False,
            )
            if result.returncode == 0:
                deno_dir = json.loads(result.stdout).get("denoDir")
        except FileNotFoundError:
            pass
    if not deno_dir:
        deno_dir = os.path.expanduser("~/.cache/deno")

    # Set DENO_DIR environment variable
    os.environ["DENO_DIR"] = deno_dir

    deno_command = [
        "deno", "run",
        "--node-modules-dir=false",
        f"--allow-read={runner_path},{deno_dir}",
        runner_path,
    ]

    return PythonInterpreter(deno_command=deno_command)


def create_qa_agent(knowledge_path: str) -> dspy.RLM:
    """
    Create a dspy.RLM-based Q&A agent.

    Args:
        knowledge_path: Path to project_knowledge.json or project_knowledge.sqlite

    Returns:
        Configured dspy.RLM instance
    """
    # Load project data
    load_project(knowledge_path)

    # Initialize LLM
    lm = dspy.LM(LLM_MODEL, api_key=LLM_API_KEY, api_base=LLM_API_BASE)
    sub_lm = dspy.LM(SUB_LLM_MODEL, api_key=LLM_API_KEY, api_base=LLM_API_BASE)

    # Embed doc schema and output language into the template to build instructions
    doc_schema = build_doc_schema(qa_tools.project_data)
    instructions = (
        INSTRUCTIONS_TEMPLATE
        .replace("<<<DOC_SCHEMA>>>", doc_schema)
        .replace("<<<RLM_OUTPUT_LANGUAGE>>>", OUTPUT_LANGUAGE)
    )

    # Create Signature and PythonInterpreter
    signature = dspy.Signature(
        "project_data, question -> answer",
        instructions,
    )

    interpreter = create_interpreter()

    # Assemble and return the RLM agent
    rlm = dspy.RLM(
        signature,
        tools=[
            qa_tools.read_source_file,
            qa_tools.get_files_using,
            qa_tools.graph_search,
        ],
        verbose=True,
        sub_lm=sub_lm,
        interpreter=interpreter,
    )

    # Set LM at module level
    rlm.set_lm(lm)

    return rlm


def ask(rlm: dspy.RLM, question: str) -> str:
    """
    Answer a question using dspy.RLM.

    Args:
        rlm: dspy.RLM instance
        question: User's question

    Returns:
        Answer text
    """
    result = rlm(
        project_data=qa_tools.project_data,
        question=question,
    )
    return result.answer


def main():
    """Interactive mode - enter questions to get answers"""
    knowledge_path = TARGET_KNOWLEDGE_PATH

    if not os.path.exists(knowledge_path):
        print(f"Error: {knowledge_path} not found.")
        print("Run uv run python main.py first.")
        sys.exit(1)

    # Initialize the RLM agent
    print(f"Loading: {knowledge_path}")
    rlm = create_qa_agent(knowledge_path)
    print("\n[OK] Initialization complete")
    print("\nEnter your question (exit: exit, quit, q)\n")

    # Interactive loop
    try:
        while True:
            try:
                question = input("> ")
                if question.lower() in ("exit", "quit", "q"):
                    break

                if not question.strip():
                    continue

                print("\nProcessing...\n")
                answer = ask(rlm, question)
                print(f"{answer}\n")

            except KeyboardInterrupt:
                break
    finally:
        # Shut down PythonInterpreter (Deno process)
        if rlm._interpreter is not None:
            rlm._interpreter.shutdown()


if __name__ == "__main__":
    main()
